### ISSUE TITLE
Changes for x64 ?

### ISSUE THREAD

**Issue by ExtReMLapin** [CPunch/QuickHook#1]
Hello,

I'm new to detouring stuff.
I'm trying to detour the lua state of the cryengine but the code in on a DLL, I already managed to get [110 functions out of 120](https://github.com/ExtReMLapin/crysis_CryScriptSystem_reversal) using IDA.

What changes exactly are needed to make it work on x64 ?

Here is what I already did : 

Added the following security that waits for the DLL to be loaded before trying to hook on :  `while (GetModuleHandle(L"CryScriptSystem.dll") == NULL) {}`

Moved all DWORDs to QWORDs `unsigned long long`

Yet it crashed.

Edit 2: 

According to IDA pro, all the functions are __fastcall, so I also moved from `__cdecl` to `__fastcall` but it still crashes right when it hook gettop

(I guessed that because on x86, at this specific time it says it managed to get the lua state, but here it crashes)

**Comment by ExtReMLapin** [comment]
I also obviously changed the addresses of the function to hook on.
The console opens, waits for any of the function but it never "hook on".

```c
#define ADDR_LOADBUFFER 0x000000003554B7A0
#define ADDR_PCALL 0x000000003554A280
#define ADDR_GETTOP 0x0000000035547BD0
#define ADDR_SETTOP 0x0000000035547BE0
#define ADDR_NEWTHREAD 0x0000000035547B90
#define ADDR_TOLSTRING 0x0000000035548A50
#define BASE(ADDR) (ADDR - 0x00400000) + (__int64)GetModuleHandle(L"CryScriptSystem.dll")
```

Addresses from here : https://github.com/ExtReMLapin/crysis_CryScriptSystem_reversal

**Comment by ExtReMLapin** [comment]
Also the address are the one from IDA which may lead to an error on my end, maybe yours are the absolute address in the file, not the one after adding loading address + filesection loading address ?

**Comment by ExtReMLapin** [comment]
The issues I have could be related to the fact i'm trying to hook on functions from a DLL, I also moved to the x86 DLL, and switched to a x86 build with static addresses to find the real issue cause (Me or the x64 attempt), it actually not even working in x86.

In IDA i rebased everything to 0x0 which gives me the static addresses : 

![](https://i.imgur.com/1ZdiuuI.png)

**Comment by CPunch** [comment]
Sadly I wrote this almost specifically for x86, you'll have to load the address into a register and jump using that since the address range for x86_64 won't fit in a standard JMP instruction. I can recommend [this](https://github.com/codectile/paradise) detouring library since I don't plan on updating this anytime soon since I rarely touch windows nowadays lol. Sorry for the late response!
